# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: HollerBell.HollerBell
PackageVersion: 1.0.20
InstallerType: nullsoft
Scope: user
InstallModes:
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
ProductCode: Holler Bell
AppsAndFeaturesEntries:
- DisplayName: Holler Bell
  Publisher: FEO
  DisplayVersion: 1.0.20
  ProductCode: Holler Bell
  InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://update.hollerbell.com/solo/dl/1062b14e9b3480aa10be927043dadbdc02c9adb28d882a2150a2cc979c697d19/Holler%20Bell_1.0.20_x64-setup.exe
  InstallerSha256: 1062B14E9B3480AA10BE927043DADBDC02C9ADB28D882A2150A2CC979C697D19
ManifestType: installer
ManifestVersion: 1.9.0
